
version: "3.3"

volumes:
    hb-cache-volume:

services:

  # NOTE: run this after the site comes up to make the kits
  # docker exec -it h-web python3 make_kits.py
  web:
    build: .
    expose:
      - "3031"
    volumes:
      - /home/hb/hiddenbeauty-models:/hiddenbeauty-models
      - /home/hb/kits:/kits
      - /home/hb/hiddenbeauty-web/hiddenbeauty/admin/uwsgi/uwsgi.ini:/code/uwsgi.ini:ro
    environment:
      - VIRTUAL_HOST=hiddenbeauty.ch
      - LETSENCRYPT_HOST=hiddenbeauty.ch
      - LETSENCRYPT_EMAIL=mayhem@gmail.com
    command: uwsgi --ini /code/uwsgi.ini

  comp:
    build: .
    expose:
      - "8080"
    volumes:
      - hb-cache-volume:/cache \
      - /home/hb/hiddenbeauty-model:/hiddenbeauty-models
      - /home/hb/hiddenbeauty-web/hiddenbeauty/admin/nginx/hb-comp.conf:/etc/nginx/nginx.conf:rw
    environment:
      - VIRTUAL_HOST=hiddenbeauty.ch
      - LETSENCRYPT_HOST=hiddenbeauty.ch
      - LETSENCRYPT_EMAIL=mayhem@gmail.com

logging:
    driver: gelf
    options:
        gelf-address: "udp://95.217.186.18:12401"
        tag: hb

networks:
  default:
    name: nginx-proxy
    external: true
